pri = int(input("enter the principal amount"))
intrest = int(input("enter the rate of intrest"))
tym = int(input("enter the time"))
si =((pri*intrest*tym)/100)
print("intrest to be payed:",si)
TA =(pri+si)
print("total ampunt to be payed back:",TA)
Mpay =(TA/(tym*12))
print("monthly amount payble:",Mpay)